class index {
    /*
    DEPARTAMENTO: DIRECCIÓN GENERAL
    DESCENDIENTES: 
    - DIRECCIÓN GENERAL
    - SECRETARIA DIRECCIÓN GENERAL
    - CENTRO DE INNOVACIÓN Y TRANSFERENCIA DE TECNOLOGÍA

    DEPARTAMENTO: DIRECCIÓN ADMINISTRATIVA
    DESCENDIENTES: 
    - DIRECCIÓN ADMINISTRATIVA
    - RECURSOS FINANCIEROS
    - RECURSOS HUMANOS
    - RECURSOS MATERIALES Y SERVICIOS GENERALES

    */
    constructor() {
        console.log("--- Comienzo proyecto ---");
    }
}

window.onload = () => new index();